### ISSUE TITLE
change documentation to match script name

### ISSUE THREAD

**Issue by yaminb** [s-n-ushakov/rename-efi-entry#1]
First off, this did exactly what I wanted. Great script.

The documentation says to run it as:
`sudo ./rename-efi-entry existing_efi_label new_efi_label [bootnum]`

in my case, I had to change that to 
Note, the .bash in the file name
`sudo ./rename-efi-entry.bash existing_efi_label new_efi_label [bootnum]`

**Comment by s-n-ushakov** [comment]
Thank you for pointing this out, and it also happened to be the good occasion to get some other pending README refinements to be pushed... :)

Please feel free to mark the issue as closed if everything looks good to you now...
